### ISSUE TITLE
Uncaught TypeError: intl is undefined

### ISSUE THREAD

**Issue by mauritsvanrees** [kitconcept/volto-quote-block#27]
Adding and then editing a quote block works, but viewing it gives an error `Uncaught TypeError: intl is undefined`.  That is on [this line](https://github.com/kitconcept/volto-quote-block/blob/cec76d2c5a3a02c10de515f8872a0323c1bdf67d/src/components/View.jsx#L40-L42).  `intl` should have come from the [`props`](https://github.com/kitconcept/volto-quote-block/blob/cec76d2c5a3a02c10de515f8872a0323c1bdf67d/src/components/View.jsx#L8), but apparently that does not work.

In other places I have seen `const intl = useSelector((state) => state.intl);`. Should we use that?
I have no idea if the best way to get `intl` differs per Volto version.

My setup: latest Volto 18 (`18.0.0-alpha.42`), Volto light theme 5.0.0, Plone 6.0.13.

**Comment by davisagli** [comment]
@mauritsvanrees @jonaspiterek Nothing passes `intl` to the props, so expecting it there is a bug.

Getting it with `useSelector` is a good way to go for function-based components.

**Comment by mauritsvanrees** [comment]
The fix is in release 1.1.2.  Thanks.
